[package]

# Note: Semantic Versioning is used: https://semver.org/
version = "1.0.0"

# Description
title = "Isaac Lab custon framework for Dyros Lab"
author = "Jaeyong Shin"
author_email = "jasonshin0537@snu.ac.kr"
maintainer = "Jaeyong Shin"
description="Extension providing custom framework interfaces and abstractions for IsaacLab."
readme  = "docs/README.md"
repository = "https://github.com/yongarry/isaaclab_dyros"
category = "robotics"
keywords = ["robotics", "learning", "ai"]

[python.pipapi]
requirements = [
    "numpy",
    "prettytable==3.3.0",
    "toml",
    "hidapi",
    "gymnasium==0.29.0",
    "trimesh",
    "websockets"
]

modules = [
    "numpy",
    "prettytable",
    "toml",
    "hid",
    "gymnasium",
    "trimesh",
    "websockets"
]

use_online_index=true

[dependencies]
"isaaclab" = {}

[core]
reloadable = false

[[python.module]]
name = "dyros"
